trajectory_planner:

# Robot Configuration Parameters
  max_vel_x: 0.25
  min_vel_x: -0.25

  max_vel_theta:  0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.4

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.1

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 10
  vtheta_samples: 30
  sim_granularity: 0.03
  angular_sim_granularity: 0.03
  heading_lookahead: 0.325

# Robot Footprint
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    radius: 0.2 # for type "circular"
    vertices: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]] # for type "polygon"
    padding: 0.01

# Cost Weights
  pdist_scale: 1.5 # higher weight make the stick to global path
  gdist_scale: 1
  occdist_scale: 0.2

  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.10
  escape_reset_theta: 1.57079632679
  escape_vel: -0.1

  dwa: false
  heading_scoring: false
  heading_scoring_timestep: 1.0

  simple_attractor: false





