scan_topics: ["/scan"] #list of LaserScan topics, max 4

# pointcloud2_topics: ["/pointcloud"] #list of PointCloud2 topics, max 4

fused_scan_topic_name: "/fused_scan_temp" #topic name of fused LaserScan

fused_pointcloud_topic_name: "/fused_pointcloud_temp" #topic name of fused PointCloud2

base_link: "base_link"

polygon: [[0.5, -0.5],[0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5]] #in float

polygon_topic_name: "/lidar_crop_polygon" #topic name of polygon

## OPTIONAL PARAMETERS
# fused_scan_options:
  # angle_increment: 0.00873 # M_PI/360.0
  # range_max: 40.0
  # range_min: 0.45
  # scan_time: 0.3333
