scan_front_topic_name: "/scan"
scan_back_topic_name: "/scan"
fused_scan_topic_name: "/fused_scan_temp"
robot_width: 10.0
robot_length: 10.0
base_link: "base_link"
polygon: [[10.0, 10.0], [10.0, -10.0], [-10.0, 10.0], [-10.0, -10.0]]

