scan_topics: ["/scan"] #list of LaserScan topics, max 4

# pointcloud2_topics: ["/pointcloud"] #list of PointCloud2 topics, max 4

fused_scan_topic_name: "/fused_scan_temp" #topic name of fused LaserScan

fused_pointcloud_topic_name: "/fused_pointcloud_temp" #topic name of fused PointCloud2

base_link: "base_link"

polygon: [[0.5, -0.5],[0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5]] #in float

polygon_topic_name: "/lidar_crop_polygon" #topic name of polygon

lidar_fusion:
  angle_increment: 0.00873 #set manually, larger or smaller value

## OPTIONAL PARAMETERS FOR CONVERTING POINTCLOUD TO LASERSCAN ##
# pointcloud2scan:
#   min_height: 0.0
#   max_height: 1.0
#   angle_min: -1.5708 # -M_PI/2
#   angle_max: 1.5708 # M_PI/2
#   angle_increment: 0.0087 # M_PI/360.0
#   scan_time: 0.3333
#   range_min: 0.45
#   range_max: 4.0
