scan_topics: ["/scan"] #list of LaserScan topics, max 4

# pointcloud2_topics: ["/pointcloud"] #list of PointCloud2 topics, max 4

fused_scan_topic_name: "/fused_scan_temp" #topic name of fused LaserScan

fused_pointcloud_topic_name: "/fused_pointcloud_temp" #topic name of fused PointCloud2

base_link: "base_link"

polygon: [[0.5, -0.5],[0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5]] #in float

polygon_topic_name: "/lidar_crop_polygon" #topic name of polygon

#ange_min and angle_max for the lidar topics to be filtered
angle_min: [50.0] #in double angle_min: [angle_min_for_scan1, angle_min_for_scan2,...] Units: degrees (0-360)
angle_max: [310.0] #in double angle_max: [angle_max_for_scan1, angle_max_for_scan2,...] Units: degrees (0-360)

## OPTIONAL PARAMETERS - if below parameters are not specified, the output fused_scan parameters will be set to the first input scan topic
# fused_scan_options:
  # angle_increment: 0.00873 # M_PI/360.0
  # range_max: 40.0
  # range_min: 0.45
  # scan_time: 0.3333
