planners:
  - {name: NavfnPlanner, type: "navfn_planner/NavfnPlanner"}
  - {name: genroute, type: "mw_global_planner/SimplePlanner"}

planner_executions:
  - {name: NavfnPlanner_execution, type: "navfn_planner/NavfnPlannerExecution"}
  - {name: genroute_execution, type: "mw_global_planner/SimplePlannerExecution"}
